# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_camera.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_Camera(object):
    def setupUi(self, Form_Camera):
        Form_Camera.setObjectName("Form_Camera")
        Form_Camera.resize(320, 273)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        Form_Camera.setFont(font)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form_Camera)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(Form_Camera)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.comboBox_ip = QtWidgets.QComboBox(self.frame)
        self.comboBox_ip.setEditable(True)
        self.comboBox_ip.setObjectName("comboBox_ip")
        self.horizontalLayout.addWidget(self.comboBox_ip)
        self.toolButton_connect = QtWidgets.QToolButton(self.frame)
        self.toolButton_connect.setObjectName("toolButton_connect")
        self.horizontalLayout.addWidget(self.toolButton_connect)
        self.toolButton_pic = QtWidgets.QToolButton(self.frame)
        self.toolButton_pic.setObjectName("toolButton_pic")
        self.horizontalLayout.addWidget(self.toolButton_pic)
        self.verticalLayout.addWidget(self.frame)
        self.label = MyLabel(Form_Camera)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMouseTracking(True)
        self.label.setAutoFillBackground(False)
        self.label.setFrameShape(QtWidgets.QFrame.Box)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.verticalLayout.setStretch(1, 10)

        self.retranslateUi(Form_Camera)
        QtCore.QMetaObject.connectSlotsByName(Form_Camera)

    def retranslateUi(self, Form_Camera):
        _translate = QtCore.QCoreApplication.translate
        Form_Camera.setWindowTitle(_translate("Form_Camera", "Form"))
        self.toolButton_connect.setText(_translate("Form_Camera", "连接"))
        self.toolButton_pic.setText(_translate("Form_Camera", "拍照"))
        self.label.setText(_translate("Form_Camera", "红外图像"))

    def closeEvent(self, event):

        event.accept()

from mylabel import MyLabel
